# Generated by Django 5.2.5 on 2025-09-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('idprofesional', models.IntegerField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('iddueño', models.IntegerField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=45, unique=True)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('fono_contacto1', models.CharField(max_length=45)),
                ('fono_contacto2', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idservicios', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_servicio', models.CharField(max_length=45)),
                ('costo_servicio', models.IntegerField()),
                ('servicioscol', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('idasistente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='principal.profesional')),
                ('tipo_acceso', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('idveterinario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='principal.profesional')),
                ('tipo_acceso', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMascota',
            fields=[
                ('idficha_mascota', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('num_chip', models.CharField(blank=True, max_length=45, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('raza', models.CharField(max_length=45)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.dueno')),
                ('asistente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('idatencion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('diagnostico', models.CharField(max_length=45)),
                ('tratamiento', models.CharField(max_length=45)),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('ficha_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.fichamascota')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('iddetalle', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('costo', models.IntegerField()),
                ('detallecol', models.CharField(blank=True, max_length=45, null=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.atencion')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.servicios')),
            ],
        ),
    ]
