# Generated by Django 5.2.5 on 2025-09-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterField(
            model_name='asistente',
            name='tipo_acceso',
            field=models.CharField(choices=[('asistente', 'Asistente'), ('veterinario', 'Veterinario')], default='asistente', max_length=45),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='tipo_acceso',
            field=models.CharField(choices=[('asistente', 'Asistente'), ('veterinario', 'Veterinario')], default='asistente', max_length=45),
        ),
    ]
