# Generated by Django 5.2.5 on 2025-09-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_profesional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamascota',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1),
        ),
    ]
