# Generated by Django 5.2.5 on 2025-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_fichamascota_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dueno',
            name='iddueño',
        ),
        migrations.AddField(
            model_name='dueno',
            name='id',
            field=models.AutoField(db_column='iddueño', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='diagnostico',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='idatencion',
            field=models.AutoField(db_column='idatencion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tratamiento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fichamascota',
            name='idficha_mascota',
            field=models.AutoField(db_column='idficha_mascota', primary_key=True, serialize=False),
        ),
    ]
