# Generated by Django 5.2.5 on 2025-09-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_remove_dueno_iddueño_dueno_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichamascota',
            old_name='raza',
            new_name='tipo_animal',
        ),
    ]
